marvel_collection/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import check_password_hash
from marvel_collection.forms import UserSignupForm, UserLoginForm
from marvel_collection.models import User, db
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            
            if User.query.filter_by(email = email).first():
                print("Account exists")
                flash("Sign-up failed, please double check your information and try again.", 'user-failed')
                return render_template('signup.html', form=form)

            print(first_name, last_name, email, password)

            user = User(first_name=first_name, last_name=last_name, email=email, password=password)
            
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your form')
    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            
            print(email, password)

            logged_user = User.query.filter(User.email==email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Incorrect email or password', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your form')
    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You successfully logged out', 'logout-success')
    return redirect(url_for('site.home'))

marvel_collection/site/routes.py
from flask import Blueprint, render_template
from flask_login.utils import login_required

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

marvel_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Marvel-Collection-API" content="API for Marvel Characters"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>Marvel Collection API</title>
</head>
<body class="bg-black">

  <!-- NavBar Here -->
  <nav class="ct-nav">
    <div>
      <a href="{{ url_for('site.home') }}" class="navbar-brand">
        <img src="{{ url_for('static', filename='images/Marvel_Studios_logo.jpg') }}" alt="Marvel Studios Public Domain Logo">
      </a>
    </div>
      <!-- Nav Items -->
    <div>
      <ul class="fw-bold" id="horizontal-list">
        <a href="{{ url_for('site.home') }}">
          <li>The Marvel Characters Project</li>
        </a>
        <a href="">
          <li>Donate</li>
        </a>
        <!-- User Auth Check for SignIn/SignUp/Profile Nav Buttons -->
        {% if current_user.is_authenticated %}
        
        <a href="{{ url_for('site.profile') }}">
          <li>Profile</li>
        </a>
        <a href="{{ url_for('auth.logout') }}">
          <li>Log Out</li>
        </a>

        {% else %}
        <a href="{{ url_for('auth.signin') }}">
          <li>Sign In</li>
        </a>
        <a href="{{ url_for('auth.signup') }}">
          <li>Sign Up Free</li>
        </a>
        
        {% endif %}
      </ul>
    </div>

  </nav>

  <!-- End of Nav -->

  {% block content %}
  {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

marvel_collection/templates/form-signin.html
<form action="" method="POST">
  {{ form.hidden_tag() }}
  <div class="form-group">
    <div class="form-floating mb-3">
      {{ form.email(type="email", class="form-control", id="floatingInput", placeholder="name@example.com", value="name@example.com") }}
      {{ form.email.label(for="floatingInput") }}
    </div>
    <div class="form-floating">
      {{ form.password(type="password", class="form-control", id="floatingPassword", placeholder="Password") }}
      {{ form.password.label(for="floatingPassword") }}
    </div>
  </div>
  <br/>
  {{ form.submit_button(class = "btn btn-secondary") }}
</form>

marvel_collection/templates/form-signup.html
<form action="" method="POST">
  {{ form.hidden_tag() }}
  <div class="form-group">
    <div class="form-floating mb-3">
      {{ form.first_name(class="form-control", id="floatingInput", placeholder="Peter", value="Peter") }}
      {{ form.first_name.label(for="floatingInput") }}
    </div>
    <div class="form-floating mb-3">
      {{ form.last_name(class="form-control", id="floatingInput", placeholder="Parker", value="Parker") }}
      {{ form.last_name.label(for="floatingInput") }}
    </div>
    <div class="form-floating mb-3">
      {{ form.email(type="email", class="form-control", id="floatingInput", placeholder="name@example.com", value="name@example.com") }}
      {{ form.email.label(for="floatingInput") }}
    </div>
    <div class="form-floating">
      {{ form.password(type="password", class="form-control", id="floatingPassword", placeholder="Password") }}
      {{ form.password.label(for="floatingPassword") }}
    </div>
  </div>
  <br/>
  {{ form.submit_button(class = "btn btn-secondary") }}
</form>